name: Backend Dev CI

on:
  pull_request:
    branches: [develop]
    paths:
      - "server/**"

defaults:
  run:
    working-directory: ./server

jobs:
  BACKEND-CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 20.8.1

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependency
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Create dev.env file
        env:
          DB_HOST_IP: ${{ secrets.SERVER_DEV_DB_HOST_IP }}
          DB_PORT: ${{ secrets.SERVER_DEV_DB_PORT }}
          DB_USER_NAME: ${{ secrets.SERVER_DEV_DB_USER_NAME }}
          DB_PASSWORD: ${{ secrets.SERVER_DEV_DB_PASSWORD }}
          DB_DATABASE_NAME: ${{ secrets.SERVER_DEV_DB_DATABASE_NAME }}
          ACCESS_ID: ${{ secrets.SERVER_ENV_ACCESS_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SERVER_ENV_SECRET_ACCESS_KEY }}
          JWT_SECRET_KEY: ${{ secrets.SERVER_ENV_JWT_SECRET_KEY }}
          GREEN_EYE_SECRET_KEY: ${{secrets.GREEN_EYE_SECRET_KEY}}
          GREEN_EYE_REQUEST_URL: ${{secrets.GREEN_EYE_REQUEST_URL}}
          CLOUD_FUNCTIONS_EXECUTE_URL: ${{secrets.CLOUD_FUNCTIONS_EXECUTE_URL}}
          CLOUD_FUNCTIONS_REQUEST_URL: ${{secrets.CLOUD_FUNCTIONS_REQUEST_URL}}
          API_GW_ACCESS_KEY: ${{secrets.API_GW_ACCESS_KEY}}
        run: |
          touch dev.env
          echo "DB_HOST_IP=$DB_HOST_IP" >> dev.env
          echo "DB_PORT=$DB_PORT" >> dev.env
          echo "DB_USER_NAME=$DB_USER_NAME" >> dev.env
          echo "DB_PASSWORD=$DB_PASSWORD" >> dev.env
          echo "DB_DATABASE_NAME=$DB_DATABASE_NAME" >> dev.env
          echo "ACCESS_ID=$ACCESS_ID" >> dev.env
          echo "SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> dev.env
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> dev.env
          echo "GREEN_EYE_SECRET_KEY=$GREEN_EYE_SECRET_KEY" >> dev.env
          echo "GREEN_EYE_REQUEST_URL=$GREEN_EYE_REQUEST_URL" >> dev.env
          echo "CLOUD_FUNCTIONS_EXECUTE_URL" >> dev.env
          echo "CLOUD_FUNCTIONS_REQUEST_URL" >> dev.env
          echo "API_GW_ACCESS_KEY" >> dev.env

      - name: Execute Test
        run: npm run test
